pearcej/opensource

- source/ch1_oss.ptx
> Grammatical Error

- source/sec_oss_source_code.ptx
> Prerequisite issue 

- source/sec_dev_virtualization.ptx
> Out of service product

- source/sec_oss_what_it_is.ptx
> Apostrophe Missing

- source/sec_oss_share_code.ptx
> 1.4.2 - Spelling Error

- source/sec_dev_basic_shell_commands.ptx
- source/sec_dev_editors.ptx
- source/sec_dev_shell_terms.ptx
- source/sec_dev_virtualization.ptx
> Chapter 4 index

- source/sec_dev_basic_shell_commands.ptx
- source/sec_dev_editors.ptx
- source/sec_dev_shell_terms.ptx
- source/sec_dev_virtualization.ptx
> Revert "Chapter 4 index"

- source/sec_community_global.ptx
Reviewed by: @thaopham03 and @nelsonxunic
> Created self-check question for 2.1

- source/sec_community_third_culture.ptx
Reviewed by @demekenega and @nelsonxunic
> Created a self-check question for section 2.2

- source/sec_community_qualities.ptx
Reviewed by @demekenega and @thaopham03
> Created self-check question for section 2.3

- source/sec_oss_matters.ptx
fix #80 
Reviewed by @demekenega @NelsonXunic @thaopham03
> Wordsmith self-check question for 1.2 #1

- source/sec_oss_source_code.ptx
fix #81 
Reviewed by @demekenega
> Wordsmith self-check question for 1.3

- source/sec_oss_contributor_mountain.ptx
> Wordsmith self-check question section 1.5 #1

- source/sec_oss_build_portfolio.ptx
> Wordsmith self-check question section 1.6 #1

- source/sec_licensing_about.ptx
> Wordsmith Self-Check Question for 3.1

- source/sec_licensing_typical.ptx
fix #144
Reviewed by @demekenega
> Wordsmith self-check question section 3.2

- source/sec_oss_matters.ptx
fix #129 
Reviewed by @demekenega
> Wordsmith self-check question for 1.2 #2

- source/sec_licensing_existing_communities.ptx
> Wordsmith self-check question section 3.3 

- source/sec_licensing_none.ptx
> Wordsmith Self-Check Question for 3.4

- source/sec_git_why_version_control.ptx
> Wordsmith Self-Check Question for 5.1

- source/sec_git_getting_started.ptx
> Wordsmith Self-Check Question for 5.2

- source/sec_git_github.ptx
Reviewed by @demekenega @NelsonXunic @eygul
> Wordsmith self-check question section 5.6 

- source/sec_git_basics.ptx
> <#>, <**>, <!>, <\> indexed

- source/sec_dev_basic_shell_commands.ptx
fix #182 #183 #184 #185 #186 #187
Reviewed by: @eygul
> Add symbols from sec_dev_basic_shell_commands.ptx

- source/sec_docu_involvement.ptx
> Wordsmith Self-Check Question for 6.2 

- source/sec_licensing_none.ptx
> Add a proper link for Unlicense

- source/sec_licensing_typical.ptx
> Add a describing word and correct visual link

- source/sec_docu_issues_bugs.ptx
- source/sec_git_getting_started.ptx
> Wordsmith self-check question section 6.4

- source/sec_git_basics.ptx
Add alt tag to external/lifecycle.png in sec_git_basics.ptx
Fix #221
> Issue221 Add alt text to lifecycle.png

- source/sec_git_getting_started.ptx
Reviewed by @AnishKharel and @timalsinab
> fix #212 by adding the description to distributed.pgn

- source/ap_git_cheat_sheet.ptx
fix #230 
reviewed by @demekenega
> Add git congif commands to cheat sheet

- source/sec_docu_issues_bugs.ptx
Added first-bug.png to 6.4.1 of the textbook, alt tag works with caption an description
> Added image, decription and caption

- source/sec_git_getting_started.ptx
> Fixed typo

- source/sec_dev_shell.ptx
Added alt text for figure 3.11, "A computer from the 1960s displaying the terminal"
> Add alt text for figure 3.1.1 img-DEC_VT100-terminal

- source/sec_community_qualities.ptx
Rephrase the sentence to improve clarity Section 2.3.3
fix #259
> Issue259 Rephrase sentence to improve clarity section 2.3.3 Type of Openness

- source/sec_dev_shell.ptx
Fix #252  
Reviewed by @tapiae1
> I added Command Line Interface Term to the Term Index

- source/sec_git_getting_started.ptx
> Added Local VCSs, Centralized VCSs, and Distributed VCSs to index

- source/sec_licensing_existing_communities.ptx
> Fixed typo in 5.3.2

- source/sec_dev_shell.ptx
> Add dual boot option for older machines

- source/sec_git_branching.ptx
Fix #294 
Reviewed by @demekenega
> Add a description tag to Figure 4.4.2.

- source/sec_dev_shell.ptx
> I added the console term to the Appendices.

- source/sec_dev_virtualization.ptx
Remove repetitive "be" in the last sentence of the section
> [#299] Fix typo in section 3.4.1

- source/sec_community_communication.ptx
Removed misplaced possessive "their" in the last sentence of the section
> [#298] Fix typo in section 2.4.2.4

- source/sec_oss_what_it_is.ptx
This updates some of the copy in chapter one to more accurately reflect the meaning of open source and the relationshiop to FOSS. This is based on an email thread of the teaching open source mailing list.
> chore: copy update concerning oss and foss - chapter 1

- source/sec_git_github.ptx
> Adding commits to an existing Pull Request does not trigger a notification, so once you push corrections, you might want to leave a comment to inform the project owner that you made the requested change.
> Fixed Grammatical issues Fixes issue #326

- source/sec_oss_source_code.ptx
> Fix Header mispelling for issue #319

- source/sec_oss_contributor_mountain.ptx
> Fix typo noted in issue #320

- source/ap_git_cheat_sheet.ptx
> Add git delete branch. fixes issue #333

- source/sec_oss_contributor_mountain.ptx
> FIxes Typo in issue #323

- source/meta_frontmatter.ptx
> Solved the Deprecates warning about elements in a titlepage Fixes Issue#332

- source/sec_community_communication.ptx
Fixes issue #336 
Fixed grammatical error in section 2.4.2 in the second sentence. 
Changed from:
"These features arise naturally from the need store code, to discuss issues related to the code, to employ version control, and other needs:"
to
"These features arise naturally from the need to store code, to discuss issues related to the code, to employ version control, and other needs:"
> Fixed grammatical error in section 2.4.2 in the second sentence #336

- source/sec_community_communication.ptx
Changed the word _term_ to _team_ in the paragraph noted in issue #327
> Fixed the typo noted in issue #327

- source/sec_git_basics.ptx
> Corrected the word from main to master Fix issue #342

- source/sec_oss_matters.ptx
Changes "Pretext or espeak" to "PreTeXt or eSpeak".
> Error#341 Fixes capitalization issue.

- source/sec_dev_editors.ptx
> Solved some grammatical errors and typos fixes issue#346

- source/sec_dev_virtualization.ptx
> Sovled the sentence's grammar Fixes Issue #347

- source/sec_community_communication.ptx
> Solved Issue 349, Section 2.4.2.1

- source/sec_git_basics.ptx
Replaced <paragraphs> tags with <subsubsection> tags which reduced the amount of text for each symbol in the index. Fixes issue #364.
> Issue #364 fix and issue #152 partial fix

- source/sec_git_github.ptx
> Fixing Issue 152, for the At Symbol
